# Version: 1.0
# released 2025.03.04: initial release
# yamllint disable rule:line-length
---
name: Enivronment Prepare
description: Create Github Release based commit tag

outputs:
  environment:
    description: "Deployment environment"
    value: ${{ steps.set-environment-and-path.outputs.ENVIRONMENT }}
  short_env:
    description: "Short environment name"
    value: ${{ steps.set-environment-and-path.outputs.SHORT_ENV }}
    
runs:
  using: composite
  steps:
    - name: Fetch target branch
      shell: bash
      if: github.event_name == 'pull_request'
      run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

    - id: set-environment-and-path
      shell: bash
      run: |
        TARGET_BRANCH=${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name}}
        if [ "$TARGET_BRANCH" = "main" ]; then
          ENVIRONMENT='["production"]'
          SHORT_ENV='["prd"]'
        elif [ "$TARGET_BRANCH" = "development" ]; then
          ENVIRONMENT='["development"]'
          SHORT_ENV='["dev"]'
        elif [ "$TARGET_BRANCH" = "staging" ]; then
          ENVIRONMENT='["staging"]'
          SHORT_ENV='["stg"]'
        fi
        echo "${ENVIRONMENT}"
        echo "${SHORT_ENV}"
        echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_OUTPUT
        echo "SHORT_ENV=${SHORT_ENV}" >> $GITHUB_OUTPUT
        echo "target_branch=${TARGET_BRANCH}" >> $GITHUB_OUTPUT
