name: 'Create Release'

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read
  pages: write
  id-token: write
  security-events: write
  pull-requests: write

jobs:
  release:
    name: 'Create Release'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with: 
        node-version: 20

    - name: Install Semantic-Release
      run: npm install -g semantic-release @semantic-release/github
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${version}
      run: npx semantic-release --debug -b main -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/github --tag-format "${VERSION}"      